Added turn indicators
ketanhwr/chain-reaction pull request #19
Opened 2017-12-13 15:44 UTC by dcoollx

Fixed EOL problem. now only shows proper changes

2017-12-14 06:05 UTC, ketanhwr requested changes
I think this is fine, take a look into my comment.

2017-12-14 06:05 UTC, ketanhwr commented on index.html
> +			<div id = "turnIndicator" >Reds turn</div>
I think you need to add `style = "color:red"` here so that the turn is known for the first time also.

2017-12-15 05:52 UTC, ketanhwr commented
@dcoollx recently, a pull request was merged that allowed more than 2 players. Therefore a few conflicts will be there and you will have to modify the logic to support more than 2 players as well.

You can either close this pull request, update your fork with the latest `ketanhwr:master` and make another pull request with the new logic, or you can rebase your pull request over my current master. I'll suggest the first since you will have a nicer commit history.

2017-12-16 00:34 UTC, closed without merging

2017-12-16 00:35 UTC, dcoollx commented
will create a new one with multiplayer logic per your request